apiVersion: v1
kind: Pod
metadata:
 name: uat-executor
spec:
  containers:
    - image: uat-docker:<tag>
      name: uat-docker
      env:
        - name: EMAIL
          valueFrom: 
            configMapKeyRef:
              name: uat-configmap
              key: email
        - name: USERNAME
          valueFrom: 
            configMapKeyRef:
              name: uat-configmap
              key: username
        - name: PASSWORD
          valueFrom: 
            configMapKeyRef:
              name: uat-configmap
              key: password
        - name: TEST_SUITE
          valueFrom: 
            configMapKeyRef:
              name: uat-configmap
              key: test_suite
        - name: ENV_PROFILE
          valueFrom: 
            configMapKeyRef:
              name: uat-configmap
              key: env_profile
        - name: RECIPIENT
          valueFrom: 
            configMapKeyRef:
              name: uat-configmap
              key: recipient
  restartPolicy: Never
  volumes:
  - name: config
    configMap:
      name: uat-configmap
